version: '3'
services:

    elasticsearch:
        image: elasticsearch:7.11.1
        ports:
            - "9200:9200"
        volumes:
            - elasticsearch_data:/usr/share/elasticsearch/data
        environment:
            - TZ=Asia/Tokyo
            - LANG=C.UTF-8
            - ELASTIC_PASSWORD=password
            - ES_JAVA_OPTS=-Xms512m -Xmx512m
            - discovery.type=single-node
            - cluster.name=docker-cluster
            - bootstrap.memory_lock=true
            - xpack.security.enabled=true
            - xpack.monitoring.collection.enabled=true

    # https://hub.docker.com/_/kibana/tags
    kibana:
        image: kibana:7.11.1
        ports:
            - 5601:5601
        environment:
            - ELASTICSEARCH_URL=http://elasticsearch:9200
            - ELASTICSEARCH_USERNAME=elastic
            - ELASTICSEARCH_PASSWORD=password
        depends_on:
            - elasticsearch

volumes:
    elasticsearch_data:
